### ISSUE TITLE
Laravel 10 Installing error

### ISSUE THREAD

**Issue by saud978** [JoDeveloper/msegat-laravel-8#4]
Error when installing

System info:
Macbook Pro (intel)
MacOS: 12.7.2 
PHP=> 8.1
Laravel => 10

Screenshot:
<img width="718" alt="Screen Shot 2024-01-01 at 12 12 03 PM" src="https://github.com/JoDeveloper/msegat-laravel-8/assets/3801360/c100bcf1-90f5-43a3-abfe-46aed919f059">

**Comment by JoDeveloper** [comment]
I've upgraded the package to laravel 10.

If you encounter any issues after the upgrade, please follow these steps:

1. **Update Composer Dependencies:**
    ```bash
    composer update
    ```

2. **Require the Latest Development Version of the Package:**
    ```bash
    composer require jodeveloper/msegat:dev-master
    ```

**Comment by saud978** [comment]
Work like a charm
This did the trick
`composer require jodeveloper/msegat:dev-master`
